### ISSUE TITLE
Meteor ROOT_URL env

### ISSUE THREAD

**Issue by timstott** [timstott/tornado#1]
Meteor won't read the `ROOT_URL` env var set in the Dockerfile or passed by `docker run`.

```
/meteor/bundle/programs/server/boot.js:205
}).run();
   ^
Error: $ROOT_URL, if specified, must be an URL
    at Error (<anonymous>)
    at Meteor.absoluteUrl.options (packages/meteor/url_server.js:8)
    at /meteor/bundle/programs/server/packages/meteor.js:1108:4
    at /meteor/bundle/programs/server/packages/meteor.js:1193:3
    at /meteor/bundle/programs/server/boot.js:168:10
```

However specifying `ROOT_URL` at the entry point command seems to work:
```
ROOT_URL=http://something.com node main.js
```

**Comment by grantcarthew** [comment]
I'm having this issue when trying to launch Meteor using systemd on Debian Jessie. Using systemd I can't use the entry point command though.

**Comment by timstott** [comment]
@grantcarthew you are spot on! I did have my URIs surrounded with single quotes.

Thank you for sharing this :+1:.
